### ISSUE TITLE
WebGL:  dynCall is not a function

### ISSUE THREAD

**Issue by glebov21** [mikerochip/unity-websocket#13]
Unity 2023
Hello. I have error "dynCall is not a function" in this place: 
https://github.com/mikerochip/unity-websocket/blob/93dfe30a155decec0a747c80fa361d0155112853/Runtime/Internal/WebSocket.jslib#L102

Publish settings: use WebAssembly.Table = true;

I think, this and similar lines must be replaced by this: 
`{{{ makeDynCall('vi', 'webSocketState.onOpen') }}}(instanceId);`

https://docs.unity3d.com/2023.2/Documentation/Manual/web-interacting-browser-example.html

**Comment by mikerochip** [comment]
It's not that simple, unfortunately, but thank you for bringing this to my attention

It looks like this was a change first introduced in [emscripten 2.0.3](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#203-09102020) which should have been included since Unity 2022.2 according to [this table](https://docs.unity3d.com/2023.2/Documentation/Manual/webgl-native-plugins-with-emscripten.html).

I guess Unity must have changed the flags it passes to build emscripten in Unity 2023.2 / Unity 6. That's kind of annoying, since this breaks backward compatibility with anything using `dyncall_` including NativeWebSocket, which this package was forked from. I guess that package is going to stay broken unless the maintainer comes back to fix it.

Anyway, Unity 2019 support would break if I made the change you're suggesting, so I'll probably have to figure out how to maintain 2 separate copies of this lib or start doing proper version pinning.

**Comment by mikerochip** [comment]
@glebov21 Took a couple tries, but I managed to do some gymnastics to get the latest commit working of this package working with all versions from 2019.4 through 2023.2+ with `WebAssembly.Table` enabled.

No changes required by users of this package, except updating to the latest package commit or using the 1.1.0 tag, whichever you like.

**Comment by glebov21** [comment]
Thank you very match!

**Comment by mikerochip** [comment]
No, thank YOU you for finding this! I think this is now the only Web-compatible WebSocket library for Unity that supports this.
