### ISSUE TITLE
Unity freezes when trying to open multiple unity-websockets (i.e. 100 connections)

### ISSUE THREAD

**Issue by stefanbursuc** [mikerochip/unity-websocket#15]
When I tried to open multiple connections to a server to stress tests some scenarios, Unity freezes and needs to be killed and restart to recover it.

**Comment by mikerochip** [comment]
Can you elaborate on what results you're seeing? As in, does it slowdown as you approach a higher number of instances or does it just immediately freeze at a certain number? Also, does your PR make Unity appear to operate normally? Is it still slow, but usable? etc.

**Comment by stefanbursuc** [comment]
I have added a small Unity Project that reproduces the issue. It tries to make 30 connections to [wss://echo.websocket.org](url)

I am not very proficient in programming with `async/await`.
I just found out where the hang occurs by commenting/uncommenting various pieces of the code.

[UnityWebSocketHangTest.zip](https://github.com/user-attachments/files/16661222/UnityWebSocketHangTest.zip)

**Comment by mikerochip** [comment]
@stefanbursuc After some testing, re-worked the code to not continue in the lock and to have a `await Task.Yield();` if no outgoing messages were detected, which felt more consistent than an arbitrary delay since it's the same task cooperation strategy used in the various async Tasks in the `WebSocketConnection` class itself. Give that a try and LMK?
